name: Images

on: workflow_dispatch

env:
  REGISTRY: ghcr.io

jobs:
  php:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        version: [ 8.3, 8.2 ]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set environment variable
        run: echo "IMAGE=${{ env.REGISTRY }}/${{ github.actor }}/php" >> $GITHUB_ENV
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image if exists
        run: docker pull ${{ env.IMAGE }}:${{ matrix.version }}
        continue-on-error: true
        id: pull
      - name: Build and push image if not pulled
        run: |
          docker build --build-arg version=${{ matrix.version }} -t ${{ env.IMAGE }}:${{ matrix.version }} - < php.Dockerfile
          docker push ${{ env.IMAGE }}:${{ matrix.version }}
        if: steps.pull.outcome != 'success'
